_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/Path/to/Base/Pretrain/Weight"
  MASK_ON: False
  BACKBONE:
    FREEZE: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: False
  ROI_HEADS:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.001
    NUM_CLASSES: 5
    FREEZE_FEAT: True
    CLS_DROPOUT: True
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ("robot_competition_voc_trainval", )
  TEST: ("robot_competition_voc_test",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (6400,) # (640,) # (3200,)
  MAX_ITER: 8000 # 800 # 4000
  CHECKPOINT_PERIOD: 500
  WARMUP_ITERS: 0
TEST:
  PCB_ENABLE: False
  PCB_MODELPATH: "/home/hanj/pyprojects/DeFRCN/datasets/ImageNetPretrained/torchvision/resnet101-5d3b4d8f.pth"
OUTPUT_DIR: "/Path/to/Output/Dir"
